version: "3.7"
services:
  db:
    image: sartography/cr-connect-db
    volumes:
      - $HOME/docker/volumes/stardrive/postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=ed_user
      - POSTGRES_PASSWORD=ed_pass
      - POSTGRES_MULTIPLE_DATABASES=stardrive,stardrive_test

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.11
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - $HOME/docker/volumes/stardrive/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300

  backend:
    image: stardrive-test-backend:latest
    ports:
      - 127.0.0.1:5000:5000
    restart: unless-stopped
    depends_on:
      - es
      - db


  frontend:
    image: stardrive-test-frontend:latest
    environment:
      - "API_URL=http://star-drive_backend_1:5000"
    ports:
      - 127.0.0.1:4200:4200
    depends_on:
      - es
      - db
      - backend
