services:
  db:
    image: postgres:17.6
    volumes:
      - $HOME/docker/volumes/autismdrive/postgres:/var/lib/postgresql/data
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - PGDATA
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:${ES_STACK_VERSION}
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - TAKE_FILE_OWNERSHIP=1
      - bootstrap.memory_lock=true
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=localhost
      - http.cors.enabled=true
      - http.max_content_length=10MB
      - http.port=${ES_PORT}
      - network.publish_host=localhost
      - xpack.license.self_generated.type=basic
      - xpack.ml.use_auto_machine_memory_percent=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    mem_limit: 2gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655350
        hard: 655350
    volumes:
      - ${HOME}/docker/volumes/autismdrive/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "${ES_HOST}:${ES_PORT}:9200"
      - "${ES_HOST}:${ES_MGMT_PORT}:9300"
