[project]
requires-python = ">=3.12,<3.13"
authors = [
    { name = "Rose Nevill", email = "rn4ee@virginia.edu" },
]
maintainers = [
    { name = "Aaron Louie", email = "4656575+ajlouie@users.noreply.github.com" },
]
description = "Autism DRIVE backend API"
name = "autismdrive"
version = "0.1.0"
readme = "README.md"
dependencies = [
    "APScheduler",
    "Flask==3.1.1",
    "Flask-Bcrypt",
    "Flask-Cors",
    "Flask-HTTPAuth",
    "Flask-Migrate",
    "PyJWT",
    "SQLAlchemy",
    "SQLAlchemy-Utils",
    "XlsxWriter",
    "alembic",
    "click",
    "elasticsearch==8.19.0",
    "elasticsearch-dsl==8.18.0",
    "flask-marshmallow",
    "googlemaps",
    "httpretty",
    "icecream",
    "idna",
    "itsdangerous",
    "marshmallow==3.26.1",
    "marshmallow-sqlalchemy==1.1.0",
    "openpyxl",
    "psycopg",
    "pycparser",
    "pydantic",
    "pydantic-settings",
    "python-dateutil",
    "pytz",
    "requests",
    "six",
    "tzlocal",
    "urllib3",
    "psycopg-c",
    "psycopg-binary",
    "uwsgi",
]

[project.urls]
homepage = "https://autismdrive.virginia.edu"
source = "https://github.com/autismdrive/autismdrive"
issues = "https://github.com/autismdrive/autismdrive/issues"
documentation = "https://github.com/autismdrive/autismdrive/blob/main/backend/README.md"
icon = "https://autismdrive.virginia.edu/favicon.ico"

[dependency-groups]
dev = [
    "coverage",
    "faker",
    "faker-biology",
    "gevent",
    "ruff",
    "traceback-with-variables",
]

[tool.ruff]
line-length = 120

[tool.setuptools.packages.find]
where = ["app"]
include = ["app"]
exclude = [
    "config",
    "example_data",
    "instance",
    "migrations",
    "tests",
]
namespaces = false
