"""empty message

Revision ID: 026293aa38f3
Revises: dae8f36249fb
Create Date: 2019-02-07 10:33:01.660586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026293aa38f3'
down_revision = 'dae8f36249fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_diagnoses_questionnaire', sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True))
    op.add_column('current_behaviors_questionnaire', sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True))
    op.add_column('developmental_questionnaire', sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True))
    op.add_column('education_questionnaire', sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True))
    op.add_column('employment_questionnaire', sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True))
    op.add_column('supports_questionnaire', sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supports_questionnaire', 'time_on_task_ms')
    op.drop_column('employment_questionnaire', 'time_on_task_ms')
    op.drop_column('education_questionnaire', 'time_on_task_ms')
    op.drop_column('developmental_questionnaire', 'time_on_task_ms')
    op.drop_column('current_behaviors_questionnaire', 'time_on_task_ms')
    op.drop_column('clinical_diagnoses_questionnaire', 'time_on_task_ms')
    # ### end Alembic commands ###
