"""empty message

Revision ID: 037429037ea4
Revises: 0c9d21ed28da
Create Date: 2019-01-30 14:42:00.864743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '037429037ea4'
down_revision = '0c9d21ed28da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identification_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('relationship_to_participant', sa.String(), nullable=True),
    sa.Column('relationship_to_participant_other', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_first_name_preferred', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('birth_city', sa.String(), nullable=True),
    sa.Column('birth_state', sa.String(), nullable=True),
    sa.Column('is_english_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guardian_demographics_questionnaire')
    op.drop_constraint('contact_questionnaire_participant_id_fkey', 'contact_questionnaire', type_='foreignkey')
    op.drop_column('contact_questionnaire', 'last_name')
    op.drop_column('contact_questionnaire', 'participant_id')
    op.drop_column('contact_questionnaire', 'is_first_name_preferred')
    op.drop_column('contact_questionnaire', 'first_name')
    op.drop_column('contact_questionnaire', 'nickname')
    op.drop_constraint('demographics_questionnaire_participant_id_fkey', 'demographics_questionnaire', type_='foreignkey')
    op.drop_constraint('demographics_questionnaire_guardian_id_fkey', 'demographics_questionnaire', type_='foreignkey')
    op.drop_column('demographics_questionnaire', 'birthdate')
    op.drop_column('demographics_questionnaire', 'middle_name')
    op.drop_column('demographics_questionnaire', 'last_name')
    op.drop_column('demographics_questionnaire', 'birth_city')
    op.drop_column('demographics_questionnaire', 'participant_id')
    op.drop_column('demographics_questionnaire', 'is_english_primary')
    op.drop_column('demographics_questionnaire', 'birth_state')
    op.drop_column('demographics_questionnaire', 'is_first_name_preferred')
    op.drop_column('demographics_questionnaire', 'guardian_id')
    op.drop_column('demographics_questionnaire', 'first_name')
    op.drop_column('demographics_questionnaire', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics_questionnaire', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('guardian_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('is_first_name_preferred', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('birth_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('is_english_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('birth_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key('demographics_questionnaire_guardian_id_fkey', 'demographics_questionnaire', 'stardrive_user', ['guardian_id'], ['id'])
    op.create_foreign_key('demographics_questionnaire_participant_id_fkey', 'demographics_questionnaire', 'stardrive_user', ['participant_id'], ['id'])
    op.add_column('contact_questionnaire', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact_questionnaire', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact_questionnaire', sa.Column('is_first_name_preferred', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('contact_questionnaire', sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contact_questionnaire', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('contact_questionnaire_participant_id_fkey', 'contact_questionnaire', 'stardrive_user', ['participant_id'], ['id'])
    op.create_table('guardian_demographics_questionnaire',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('guardian_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('race_ethnicity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_english_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('relationship_to_child', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('race_ethnicity_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relationship_to_child_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender_identity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender_identity_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['stardrive_user.id'], name='guardian_demographics_questionnaire_guardian_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='guardian_demographics_questionnaire_pkey')
    )
    op.drop_table('identification_questionnaire')
    # ### end Alembic commands ###
