"""empty message

Revision ID: 0bdde178b75e
Revises: 715890d8a5b4
Create Date: 2020-07-09 16:45:20.523204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bdde178b75e'
down_revision = '715890d8a5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_user_event_id_fkey' ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], name='event_user_user_id_fkey' ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event', sa.Column('includes_registration', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('max_users', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('post_survey_link', sa.String(), nullable=True))
    op.add_column('event', sa.Column('webinar_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'webinar_link')
    op.drop_column('event', 'post_survey_link')
    op.drop_column('event', 'max_users')
    op.drop_column('event', 'includes_registration')
    op.drop_table('event_user')
    # ### end Alembic commands ###
