"""empty message

Revision ID: 122b7ade20c7
Revises: 21d0f2b252c5
Create Date: 2021-04-28 14:18:30.488558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '122b7ade20c7'
down_revision = '21d0f2b252c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermeta',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('self_has_guardian', sa.Boolean(), nullable=True),
    sa.Column('self_own_guardian', sa.Boolean(), nullable=True),
    sa.Column('guardian_legal', sa.Boolean(), nullable=True),
    sa.Column('guardian_not_legal', sa.Boolean(), nullable=True),
    sa.Column('professional', sa.Boolean(), nullable=True),
    sa.Column('interested', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usermeta')
    # ### end Alembic commands ###
