"""empty message

Revision ID: 12b4edc6125b
Revises: c29fc0a07930
Create Date: 2020-04-16 15:55:00.532956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12b4edc6125b'
down_revision = 'c29fc0a07930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('investigator_organization_id_fkey', 'investigator', type_='foreignkey')
    op.drop_column('investigator', 'organization_id')
    op.drop_constraint('resource_organization_id_fkey', 'resource', type_='foreignkey')
    op.drop_column('resource', 'organization_id')
    op.drop_constraint('study_organization_id_fkey', 'study', type_='foreignkey')
    op.drop_column('study', 'organization_id')
    op.drop_table('organization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_pkey')
    )
    op.add_column('study', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('study_organization_id_fkey', 'study', 'organization', ['organization_id'], ['id'])
    op.add_column('resource', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('resource_organization_id_fkey', 'resource', 'organization', ['organization_id'], ['id'])
    op.add_column('investigator', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('investigator_organization_id_fkey', 'investigator', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###
