"""empty message

Revision ID: 1516b659add3
Revises: 9b9102347500
Create Date: 2019-08-14 13:32:15.315698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1516b659add3'
down_revision = '9b9102347500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('short_description', sa.String(), nullable=True))
    op.add_column('study', sa.Column('short_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'short_title')
    op.drop_column('study', 'short_description')
    # ### end Alembic commands ###
