"""empty message

Revision ID: 15cfedb47914
Revises: 0a96d64ea510
Create Date: 2020-01-30 11:58:02.619022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15cfedb47914'
down_revision = '0a96d64ea510'
branch_labels = None
depends_on = None

old_options = ('admin', 'user')
new_options = sorted(old_options + ('test', 'researcher', 'editor'))

old_type = sa.Enum(*old_options, name='role')
new_type = sa.Enum(*new_options, name='role')
tmp_type = sa.Enum(*new_options, name='_role')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a temporary "_relationship" type, convert and drop the "old" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.alter_column('stardrive_user', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='role'),
               type_=sa.Enum('admin', 'test', 'researcher', 'editor', 'user', name='_role'),
               existing_nullable=True, postgresql_using="role::text::_role")
    old_type.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "new" role type
    new_type.create(op.get_bind(), checkfirst=False)
    op.alter_column('stardrive_user', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='_role'),
               type_=sa.Enum('admin', 'test', 'researcher', 'editor', 'user', name='role'),
               existing_nullable=True, postgresql_using="role::text::role")
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a temporary "_relationship" type, convert and drop the "new" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.alter_column('stardrive_user', 'role',
               existing_type=sa.Enum('admin', 'test', 'researcher', 'editor', 'user', name='role'),
               type_=postgresql.ENUM('admin', 'user', name='_role'),
                    existing_nullable=True, postgresql_using="role::text::_role")
    new_type.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "old" role type
    old_type.create(op.get_bind(), checkfirst=False)
    op.alter_column('stardrive_user', 'role',
               existing_type=sa.Enum('admin', 'test', 'researcher', 'editor', 'user', name='_role'),
               type_=postgresql.ENUM('admin', 'user', name='role'),
                    existing_nullable=True, postgresql_using="role::text::role")
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
    op.alter_column('stardrive_user', 'role',
               existing_type=sa.Enum('admin', 'test', 'researcher', 'editor', 'user', name='role'),
               type_=postgresql.ENUM('admin', 'user', name='role'),
               existing_nullable=True)
    # ### end Alembic commands ###
