"""empty message

Revision ID: 16e705703c60
Revises: 6bfa0312ba62
Create Date: 2021-05-10 16:31:51.748351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16e705703c60'
down_revision = '6bfa0312ba62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermeta', 'self_relationship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermeta', sa.Column('self_relationship', postgresql.ENUM('dependent', 'self_guardian', 'self_interested', 'self_participant', 'self_professional', name='relationship'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
