"""empty message

Revision ID: 17002734af75
Revises: 98c7920d1570
Create Date: 2019-01-28 14:26:18.100783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17002734af75'
down_revision = '98c7920d1570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_history_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('self_identifies_autistic', sa.Boolean(), nullable=True),
    sa.Column('has_autism_diagnosis', sa.Boolean(), nullable=True),
    sa.Column('years_old_at_first_diagnosis', sa.Integer(), nullable=True),
    sa.Column('who_diagnosed', sa.String(), nullable=True),
    sa.Column('who_diagnosed_other', sa.String(), nullable=True),
    sa.Column('where_diagnosed', sa.String(), nullable=True),
    sa.Column('where_diagnosed_other', sa.String(), nullable=True),
    sa.Column('partner_centers_evaluation', sa.String(), nullable=True),
    sa.Column('gives_permission_to_link_evaluation_data', sa.Boolean(), nullable=True),
    sa.Column('has_iq_test', sa.Boolean(), nullable=True),
    sa.Column('recent_iq_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_history_questionnaire')
    # ### end Alembic commands ###
