"""empty message

Revision ID: 172c83430213
Revises: 694e37e7d38a
Create Date: 2019-09-23 16:05:58.261707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172c83430213'
down_revision = '694e37e7d38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('eligibility_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'eligibility_url')
    # ### end Alembic commands ###
