"""empty message

Revision ID: 1a3755aa3e6f
Revises: 37f5b44d035d
Create Date: 2019-04-22 15:21:51.747719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3755aa3e6f'
down_revision = '37f5b44d035d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistive_device', sa.Column('type_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistive_device', 'type_group')
    # ### end Alembic commands ###
