"""empty message

Revision ID: 1a6ea20ed002
Revises: 9b14a3e90c8e
Create Date: 2020-12-04 14:52:15.696019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a6ea20ed002'
down_revision = '9b14a3e90c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_session_assessment_questionnaire',
    sa.Column('is_task_complete', sa.Boolean(), nullable=True),
    sa.Column('has_challenging_behavior', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True),
    sa.Column('date_introduced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_mastered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_booster_required', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_booster_mastered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_attempted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_level', sa.Enum('none', 'shadow', 'partial_physical', 'full_physical', name='chainpromptlevel'), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_session_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chain_session_assessment_questionnaire_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chain_session_assessment_questionnaire_id'], ['chain_session_assessment_questionnaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('study_user', 'status',
               existing_type=postgresql.ENUM('inquiry_sent', 'enrolled', name='study_user_status'),
               type_=sa.Enum('inquiry_sent', 'enrolled', name='study_user_status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_user', 'status',
               existing_type=sa.Enum('inquiry_sent', 'enrolled', name='study_user_status'),
               type_=postgresql.ENUM('inquiry_sent', 'enrolled', name='study_user_status'),
               existing_nullable=True)
    op.drop_table('chain_session_step')
    op.drop_table('chain_session_assessment_questionnaire')
    # ### end Alembic commands ###
