"""empty message

Revision ID: 1dbc5d6304d8
Revises: 704f78a74e54
Create Date: 2019-03-05 14:02:35.646869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbc5d6304d8'
down_revision = '704f78a74e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stardrive_participant', sa.Column('avatar_color', sa.String(), nullable=True))
    op.add_column('stardrive_participant', sa.Column('avatar_icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stardrive_participant', 'avatar_icon')
    op.drop_column('stardrive_participant', 'avatar_color')
    # ### end Alembic commands ###
