"""empty message

Revision ID: 1f216d99061b
Revises: 46c352587593
Create Date: 2019-07-08 12:37:27.933473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f216d99061b'
down_revision = '46c352587593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('errors', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_log')
    # ### end Alembic commands ###
