"""empty message

Revision ID: 1f2939156dde
Revises: e8692e08942d
Create Date: 2019-09-04 13:54:23.551586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2939156dde'
down_revision = 'e8692e08942d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zip_code')
    # ### end Alembic commands ###
