"""empty message

Revision ID: 204f00c31973
Revises: 7173ef02d6c7
Create Date: 2019-02-18 16:58:26.088745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '204f00c31973'
down_revision = '7173ef02d6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_history_dependent_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('self_identifies_autistic', sa.Boolean(), nullable=True),
    sa.Column('has_autism_diagnosis', sa.Boolean(), nullable=True),
    sa.Column('years_old_at_first_diagnosis', sa.Integer(), nullable=True),
    sa.Column('who_diagnosed', sa.String(), nullable=True),
    sa.Column('who_diagnosed_other', sa.String(), nullable=True),
    sa.Column('where_diagnosed', sa.String(), nullable=True),
    sa.Column('where_diagnosed_other', sa.String(), nullable=True),
    sa.Column('partner_centers_evaluation', sa.String(), nullable=True),
    sa.Column('gives_permission_to_link_evaluation_data', sa.Boolean(), nullable=True),
    sa.Column('has_iq_test', sa.Boolean(), nullable=True),
    sa.Column('recent_iq_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_history_self_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('self_identifies_autistic', sa.Boolean(), nullable=True),
    sa.Column('has_autism_diagnosis', sa.Boolean(), nullable=True),
    sa.Column('years_old_at_first_diagnosis', sa.Integer(), nullable=True),
    sa.Column('who_diagnosed', sa.String(), nullable=True),
    sa.Column('who_diagnosed_other', sa.String(), nullable=True),
    sa.Column('where_diagnosed', sa.String(), nullable=True),
    sa.Column('where_diagnosed_other', sa.String(), nullable=True),
    sa.Column('partner_centers_evaluation', sa.String(), nullable=True),
    sa.Column('gives_permission_to_link_evaluation_data', sa.Boolean(), nullable=True),
    sa.Column('has_iq_test', sa.Boolean(), nullable=True),
    sa.Column('recent_iq_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('evaluation_history_questionnaire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_history_questionnaire',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('self_identifies_autistic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_autism_diagnosis', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('years_old_at_first_diagnosis', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('who_diagnosed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('who_diagnosed_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('where_diagnosed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('where_diagnosed_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('partner_centers_evaluation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gives_permission_to_link_evaluation_data', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_iq_test', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recent_iq_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_on_task_ms', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], name='evaluation_history_questionnaire_participant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], name='evaluation_history_questionnaire_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='evaluation_history_questionnaire_pkey')
    )
    op.drop_table('evaluation_history_self_questionnaire')
    op.drop_table('evaluation_history_dependent_questionnaire')
    # ### end Alembic commands ###
