"""empty message

Revision ID: 221895fbe0af
Revises: 838f47fa598e
Create Date: 2020-02-25 12:07:59.829352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221895fbe0af'
down_revision = '838f47fa598e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('insurance', sa.String(), nullable=True))
    op.add_column('resource', sa.Column('languages', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('resource', sa.Column('phone_extension', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'phone_extension')
    op.drop_column('resource', 'languages')
    op.drop_column('resource', 'insurance')
    # ### end Alembic commands ###
