"""empty message

Revision ID: 27bc773947aa
Revises: 8ddf84a5e50d
Create Date: 2019-04-18 14:09:43.213634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bc773947aa'
down_revision = '8ddf84a5e50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistive_device', 'description')
    op.drop_column('therapy', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapy', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assistive_device', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
