"""empty message

Revision ID: 27cc51af7a1c
Revises: 1a972481aecc
Create Date: 2019-09-04 13:17:02.854059

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27cc51af7a1c'
down_revision = '1a972481aecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_user', 'status')
    # ### end Alembic commands ###
    study_user_status = postgresql.ENUM('inquiry_sent', 'enrolled', name='study_user_status')
    study_user_status.create(op.get_bind())
    op.add_column('study_user', sa.Column('status', sa.Enum('inquiry_sent', 'enrolled', name='study_user_status'), nullable=True))


def downgrade():
    op.drop_column('study_user', 'status')
    op.execute("DROP TYPE study_user_status;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_user', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
