"""empty message

Revision ID: 2c365502c9ab
Revises: 74b4469fdbda
Create Date: 2018-12-14 10:14:09.162823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c365502c9ab'
down_revision = '74b4469fdbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stardrive_user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stardrive_user', 'email_verified')
    # ### end Alembic commands ###
