"""empty message

Revision ID: 2fd0ab60fe3a
Revises: 29012e868555
Create Date: 2019-02-22 13:39:39.314912

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fd0ab60fe3a'
down_revision = '29012e868555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stardrive_user', 'role')
    # ### end Alembic commands ###
    role = postgresql.ENUM('admin', 'user', name='role')
    role.create(op.get_bind())
    op.add_column('stardrive_user', sa.Column('role', sa.Enum('admin', 'user', name='role'), nullable=True))


def downgrade():
    op.drop_column('stardrive_user', 'role')
    op.execute("DROP TYPE role;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stardrive_user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
