"""empty message

Revision ID: 31a5e1a01a84
Revises: 885af8614bd7
Create Date: 2019-04-25 16:52:13.173243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a5e1a01a84'
down_revision = '885af8614bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('bio_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_investigator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('investigator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investigator_id'], ['investigator.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('study', 'principal_investigator')
    op.drop_column('study', 'pi_description')
    op.drop_column('study', 'pi_bio_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('pi_bio_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('study', sa.Column('pi_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('study', sa.Column('principal_investigator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('study_investigator')
    op.drop_table('investigator')
    # ### end Alembic commands ###
