"""empty message

Revision ID: 38cb1825439a
Revises: 5fb917adc751
Create Date: 2019-03-07 14:30:21.605450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cb1825439a'
down_revision = '5fb917adc751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_profile_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('professional_identity', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('professional_identity_other', sa.String(), nullable=True),
    sa.Column('learning_interests', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('learning_interests_other', sa.String(), nullable=True),
    sa.Column('currently_work_with_autistic', sa.Boolean(), nullable=True),
    sa.Column('previous_work_with_autistic', sa.Boolean(), nullable=True),
    sa.Column('length_work_with_autistic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professional_profile_questionnaire')
    # ### end Alembic commands ###
