"""empty message

Revision ID: 398615e6b6d8
Revises: fd29a4bf6b22
Create Date: 2019-05-09 10:00:24.339640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '398615e6b6d8'
down_revision = 'fd29a4bf6b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_organization_id_fkey', 'location', type_='foreignkey')
    op.create_foreign_key('location_resource_id_fkey', 'location', 'resource', ['id'], ['id'])
    op.drop_column('location', 'organization_id')
    op.drop_column('location', 'last_updated')
    op.drop_column('location', 'phone')
    op.drop_column('location', 'title')
    op.drop_column('location', 'website')
    op.drop_column('location', 'description')
    op.add_column('resource', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'type')
    op.add_column('location', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('location_resource_id_fkey', 'location', type_='foreignkey')
    op.create_foreign_key('location_organization_id_fkey', 'location', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###
