"""empty message

Revision ID: 453728f0baa6
Revises: e588ae3d8de8
Create Date: 2019-02-22 10:11:45.063357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '453728f0baa6'
down_revision = 'e588ae3d8de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_participant')
    op.add_column('stardrive_participant', sa.Column('relationship', sa.Enum('self_participant', 'self_guardian', 'dependent', name='relationship'), nullable=True))
    op.add_column('stardrive_participant', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stardrive_participant', 'stardrive_user', ['user_id'], ['id'])
    op.drop_column('stardrive_participant', 'first_name')
    op.drop_column('stardrive_participant', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stardrive_participant', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stardrive_participant', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stardrive_participant', type_='foreignkey')
    op.drop_column('stardrive_participant', 'user_id')
    op.drop_column('stardrive_participant', 'relationship')
    op.create_table('user_participant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relationship', postgresql.ENUM('self_participant', 'self_guardian', 'dependent', name='relationship'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], name='user_participant_participant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], name='user_participant_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_participant_pkey')
    )
    # ### end Alembic commands ###
