"""empty message

Revision ID: 4de2d265b186
Revises: 6a87de41a23c
Create Date: 2019-02-01 16:07:35.466350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de2d265b186'
down_revision = '6a87de41a23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_behaviors_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('verbal_ability', sa.String(), nullable=True),
    sa.Column('concerning_behaviors', sa.String(), nullable=True),
    sa.Column('has_academic_difficulties', sa.Boolean(), nullable=True),
    sa.Column('academic_difficulty_areas', sa.String(), nullable=True),
    sa.Column('academic_difficulty_other', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_behaviors_questionnaire')
    # ### end Alembic commands ###
