"""empty message

Revision ID: 57bbd20fabbc
Revises: 9b976b7f1cfa
Create Date: 2019-05-14 15:16:27.020114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57bbd20fabbc'
down_revision = '9b976b7f1cfa'
branch_labels = None
depends_on = None

old_options = ('currently_enrolling', 'data_collection_complete', 'results_being_analyzed', 'study_results_published')
new_options = ('currently_enrolling', 'study_in_progress', 'results_being_analyzed', 'study_results_published')

old_type = sa.Enum(*old_options, name='status')
new_type = sa.Enum(*new_options, name='status')
tmp_type = sa.Enum(*new_options, name='_status')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a temporary "_status" type, convert and drop the "old" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.alter_column('study', 'status',
               existing_type=postgresql.ENUM('currently_enrolling', 'data_collection_complete', 'results_being_analyzed', 'study_results_published', name='status'),
               type_=sa.Enum('currently_enrolling', 'study_in_progress', 'results_being_analyzed', 'study_results_published', name='_status'),
               existing_nullable=True, postgresql_using="status::text::_status")
    old_type.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "new" status type
    new_type.create(op.get_bind(), checkfirst=False)
    op.alter_column('study', 'status',
               existing_type=postgresql.ENUM('currently_enrolling', 'data_collection_complete', 'results_being_analyzed', 'study_results_published', name='_status'),
               type_=sa.Enum('currently_enrolling', 'study_in_progress', 'results_being_analyzed', 'study_results_published', name='status'),
               existing_nullable=True, postgresql_using="status::text::status")
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a temporary "_status" type, convert and drop the "new" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.alter_column('study', 'status',
               existing_type=sa.Enum('currently_enrolling', 'study_in_progress', 'results_being_analyzed', 'study_results_published', name='status'),
               type_=postgresql.ENUM('currently_enrolling', 'data_collection_complete', 'results_being_analyzed', 'study_results_published', name='_status'),
               existing_nullable=True, postgresql_using="status::text::_status")
    new_type.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "old" status type
    old_type.create(op.get_bind(), checkfirst=False)
    op.alter_column('study', 'status',
               existing_type=sa.Enum('currently_enrolling', 'study_in_progress', 'results_being_analyzed', 'study_results_published', name='_status'),
               type_=postgresql.ENUM('currently_enrolling', 'data_collection_complete', 'results_being_analyzed', 'study_results_published', name='status'),
               existing_nullable=True, postgresql_using="status::text::status")
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
