"""empty message

Revision ID: 5a782369bf8a
Revises: 38f0fba25172
Create Date: 2021-05-10 13:58:01.797111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a782369bf8a'
down_revision = '38f0fba25172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermeta', sa.Column('guardian', sa.Boolean(), nullable=True))
    op.add_column('usermeta', sa.Column('guardian_has_dependent', sa.Boolean(), nullable=True))
    op.add_column('usermeta', sa.Column('self_participant', sa.Boolean(), nullable=True))
    op.drop_column('usermeta', 'guardian_not_legal')
    op.drop_column('usermeta', 'guardian_legal')
    op.drop_column('usermeta', 'self_own_guardian')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermeta', sa.Column('self_own_guardian', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('usermeta', sa.Column('guardian_legal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('usermeta', sa.Column('guardian_not_legal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('usermeta', 'self_participant')
    op.drop_column('usermeta', 'guardian_has_dependent')
    op.drop_column('usermeta', 'guardian')
    # ### end Alembic commands ###
