"""empty message

Revision ID: 5c8481ca872f
Revises: e588ae3d8de8
Create Date: 2019-02-20 16:55:17.090729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c8481ca872f'
down_revision = 'e588ae3d8de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_diagnoses_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('time_on_task_ms', sa.BigInteger(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('developmental', sa.String(), nullable=True),
    sa.Column('developmental_other', sa.String(), nullable=True),
    sa.Column('mental_health', sa.String(), nullable=True),
    sa.Column('mental_health_other', sa.String(), nullable=True),
    sa.Column('medical', sa.String(), nullable=True),
    sa.Column('medical_other', sa.String(), nullable=True),
    sa.Column('genetic', sa.String(), nullable=True),
    sa.Column('genetic_other', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clinical_diagnoses_self_questionnaire')
    op.drop_table('clinical_diagnoses_dependent_questionnaire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_diagnoses_dependent_questionnaire',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_on_task_ms', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('developmental', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('developmental_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mental_health', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mental_health_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('medical', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('medical_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genetic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genetic_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], name='clinical_diagnoses_dependent_questionnaire_participant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], name='clinical_diagnoses_dependent_questionnaire_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='clinical_diagnoses_dependent_questionnaire_pkey')
    )
    op.create_table('clinical_diagnoses_self_questionnaire',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_on_task_ms', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('developmental', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('developmental_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mental_health', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mental_health_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('medical', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('medical_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genetic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genetic_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], name='clinical_diagnoses_self_questionnaire_participant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], name='clinical_diagnoses_self_questionnaire_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='clinical_diagnoses_self_questionnaire_pkey')
    )
    op.drop_table('clinical_diagnoses_questionnaire')
    # ### end Alembic commands ###
