"""empty message

Revision ID: 5cd8941ace02
Revises: 16e705703c60
Create Date: 2021-05-11 14:45:09.845296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cd8941ace02'
down_revision = '16e705703c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermeta', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('usermeta_user_id_fkey', 'usermeta', type_='foreignkey')
    op.create_foreign_key(None, 'usermeta', 'stardrive_user', ['id'], ['id'])
    op.drop_column('usermeta', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermeta', sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'usermeta', type_='foreignkey')
    op.create_foreign_key('usermeta_user_id_fkey', 'usermeta', 'stardrive_user', ['user_id'], ['id'])
    op.drop_column('usermeta', 'id')
    # ### end Alembic commands ###
