"""empty message

Revision ID: 5cdc5e06da9c
Revises: 33f1c7b1b33c
Create Date: 2019-01-24 15:17:21.342973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdc5e06da9c'
down_revision = '33f1c7b1b33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardian_demographics_questionnaire', sa.Column('race_ethnicity_other', sa.String(), nullable=True))
    op.add_column('guardian_demographics_questionnaire', sa.Column('relationship_to_child_other', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guardian_demographics_questionnaire', 'relationship_to_child_other')
    op.drop_column('guardian_demographics_questionnaire', 'race_ethnicity_other')
    # ### end Alembic commands ###
