"""empty message

Revision ID: 5ce71490be7b
Revises: b215d91f57df
Create Date: 2021-05-14 16:06:38.731016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ce71490be7b'
down_revision = 'b215d91f57df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_session_step', sa.Column('num_stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chain_session_step', 'num_stars')
    # ### end Alembic commands ###
