"""auto

Revision ID: 5d42436b6c60
Revises: 4bb452441c4e
Create Date: 2025-08-06 10:09:45.894242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d42436b6c60'
down_revision = '4bb452441c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
