"""empty message

Revision ID: 61bf48b5ca88
Revises: 7958ca181015
Create Date: 2019-04-29 15:33:33.898662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bf48b5ca88'
down_revision = '7958ca181015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supports_questionnaire', sa.Column('alternative_med', sa.String(), nullable=True))
    op.add_column('supports_questionnaire', sa.Column('alternative_med_other', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supports_questionnaire', 'alternative_med_other')
    op.drop_column('supports_questionnaire', 'alternative_med')
    # ### end Alembic commands ###
