"""empty message

Revision ID: 632e0d0b5b5a
Revises: ccd95502a214
Create Date: 2019-02-05 09:27:36.284243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632e0d0b5b5a'
down_revision = 'ccd95502a214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_behaviors_questionnaire', sa.Column('concerning_behaviors_other', sa.String(), nullable=True))
    op.add_column('current_behaviors_questionnaire', sa.Column('dependent_verbal_ability', sa.String(), nullable=True))
    op.add_column('current_behaviors_questionnaire', sa.Column('self_verbal_ability', sa.String(), nullable=True))
    op.drop_column('current_behaviors_questionnaire', 'verbal_ability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_behaviors_questionnaire', sa.Column('verbal_ability', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('current_behaviors_questionnaire', 'self_verbal_ability')
    op.drop_column('current_behaviors_questionnaire', 'dependent_verbal_ability')
    op.drop_column('current_behaviors_questionnaire', 'concerning_behaviors_other')
    # ### end Alembic commands ###
