"""empty message

Revision ID: 644bff9ebd49
Revises: 4de2d265b186
Create Date: 2019-02-01 16:15:45.407644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644bff9ebd49'
down_revision = '4de2d265b186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_diagnoses_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('developmental', sa.String(), nullable=True),
    sa.Column('mental_health', sa.String(), nullable=True),
    sa.Column('medical', sa.String(), nullable=True),
    sa.Column('genetic_conditions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinical_diagnoses_questionnaire')
    # ### end Alembic commands ###
