"""empty message

Revision ID: 68e16832d52a
Revises: 721544353e4e
Create Date: 2020-01-16 11:12:38.698780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e16832d52a'
down_revision = '721544353e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_change_log', sa.Column('resource_title', sa.String(), nullable=True))
    op.add_column('resource_change_log', sa.Column('user_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_change_log', 'user_email')
    op.drop_column('resource_change_log', 'resource_title')
    # ### end Alembic commands ###
