"""empty message

Revision ID: 6bfa0312ba62
Revises: 5a782369bf8a
Create Date: 2021-05-10 14:49:32.300588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bfa0312ba62'
down_revision = '5a782369bf8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermeta', sa.Column('self_relationship', sa.Enum('self_participant', 'self_guardian', 'dependent', 'self_professional', 'self_interested', name='relationship'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermeta', 'self_relationship')
    # ### end Alembic commands ###
