"""empty message

Revision ID: 704f78a74e54
Revises: 6366de224eec
Create Date: 2019-03-01 16:47:08.779197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704f78a74e54'
down_revision = '6366de224eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_diagnoses_questionnaire', 'developmental',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[clinical_diagnoses_questionnaire]') 
    op.alter_column('clinical_diagnoses_questionnaire', 'genetic',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[clinical_diagnoses_questionnaire]') 
    op.alter_column('clinical_diagnoses_questionnaire', 'medical',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[clinical_diagnoses_questionnaire]') 
    op.alter_column('clinical_diagnoses_questionnaire', 'mental_health',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[clinical_diagnoses_questionnaire]') 
    op.alter_column('current_behaviors_dependent_questionnaire', 'academic_difficulty_areas',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[current_behaviors_dependent_questionnaire]') 
    op.alter_column('current_behaviors_dependent_questionnaire', 'concerning_behaviors',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[current_behaviors_dependent_questionnaire]') 
    op.alter_column('current_behaviors_self_questionnaire', 'academic_difficulty_areas',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[current_behaviors_self_questionnaire]') 
    op.alter_column('current_behaviors_self_questionnaire', 'self_verbal_ability',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[current_behaviors_self_questionnaire]') 
    op.alter_column('demographics_questionnaire', 'race_ethnicity',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[demographics_questionnaire]') 
    op.alter_column('education_dependent_questionnaire', 'school_services',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[education_dependent_questionnaire]') 
    op.alter_column('education_self_questionnaire', 'school_services',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[education_self_questionnaire]') 
    op.alter_column('evaluation_history_dependent_questionnaire', 'partner_centers_evaluation',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[evaluation_history_dependent_questionnaire]') 
    op.alter_column('evaluation_history_self_questionnaire', 'partner_centers_evaluation',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[evaluation_history_self_questionnaire]') 
    op.alter_column('home_dependent_questionnaire', 'dependent_living_situation',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               existing_nullable=True,postgresql_using='array[home_dependent_questionnaire]') 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_dependent_questionnaire', 'dependent_living_situation',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('evaluation_history_self_questionnaire', 'partner_centers_evaluation',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('evaluation_history_dependent_questionnaire', 'partner_centers_evaluation',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('education_self_questionnaire', 'school_services',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('education_dependent_questionnaire', 'school_services',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('demographics_questionnaire', 'race_ethnicity',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('current_behaviors_self_questionnaire', 'self_verbal_ability',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('current_behaviors_self_questionnaire', 'academic_difficulty_areas',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('current_behaviors_dependent_questionnaire', 'concerning_behaviors',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('current_behaviors_dependent_questionnaire', 'academic_difficulty_areas',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('clinical_diagnoses_questionnaire', 'mental_health',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('clinical_diagnoses_questionnaire', 'medical',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('clinical_diagnoses_questionnaire', 'genetic',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    op.alter_column('clinical_diagnoses_questionnaire', 'developmental',
               existing_type=sa.ARRAY(sa.VARCHAR()),
               type_=sa.VARCHAR(),
               existing_nullable=True) 
    # ### end Alembic commands ###
