"""empty message

Revision ID: 715890d8a5b4
Revises: ff26b0cf1ede
Create Date: 2020-05-27 15:15:44.849889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '715890d8a5b4'
down_revision = 'ff26b0cf1ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('survey_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'survey_url')
    # ### end Alembic commands ###
