"""empty message

Revision ID: 721544353e4e
Revises: b75bc0077b6b
Create Date: 2020-01-16 10:35:03.417560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721544353e4e'
down_revision = 'b75bc0077b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resource_change_log_resource_id_fkey', 'resource_change_log', type_='foreignkey')
    op.drop_constraint('resource_change_log_user_id_fkey', 'resource_change_log', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('resource_change_log_user_id_fkey', 'resource_change_log', 'stardrive_user', ['user_id'], ['id'])
    op.create_foreign_key('resource_change_log_resource_id_fkey', 'resource_change_log', 'resource', ['resource_id'], ['id'])
    # ### end Alembic commands ###
