"""empty message

Revision ID: 7958ca181015
Revises: 31a5e1a01a84
Create Date: 2019-04-29 15:10:59.142273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7958ca181015'
down_revision = '31a5e1a01a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('symptom', sa.String(), nullable=True))
    op.add_column('medication', sa.Column('symptom_other', sa.String(), nullable=True))
    op.drop_column('medication', 'dosage')
    op.drop_column('medication', 'time_frame')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('time_frame', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('medication', sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('medication', 'symptom_other')
    op.drop_column('medication', 'symptom')
    # ### end Alembic commands ###
