"""empty message

Revision ID: 79c463336307
Revises: 2fed03895153
Create Date: 2018-12-20 12:06:38.478060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c463336307'
down_revision = '2fed03895153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resource', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource', 'organization', ['organization_id'], ['id'])
    op.drop_column('resource', 'organization')
    op.add_column('study', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study', 'organization', ['organization_id'], ['id'])
    op.add_column('training', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'organization_id')
    op.drop_constraint(None, 'study', type_='foreignkey')
    op.drop_column('study', 'organization_id')
    op.add_column('resource', sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column('resource', 'organization_id')
    op.drop_table('organization')
    # ### end Alembic commands ###
