"""empty message

Revision ID: 7ede01846a31
Revises: 1f216d99061b
Create Date: 2019-07-25 15:18:17.178640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ede01846a31'
down_revision = '1f216d99061b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_transfer_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('date_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('alerts_sent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_transfer_log_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_transfer_log_id', sa.Integer(), nullable=True),
    sa.Column('date_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('errors', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['data_transfer_log_id'], ['data_transfer_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('export_log')
    op.drop_table('import_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_started', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('successful', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('success_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failure_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('errors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='import_log_pkey')
    )
    op.create_table('export_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('available_records', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alerts_sent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='export_log_pkey')
    )
    op.drop_table('data_transfer_log_detail')
    op.drop_table('data_transfer_log')
    # ### end Alembic commands ###
