"""empty message

Revision ID: 838f47fa598e
Revises: 15cfedb47914
Create Date: 2020-02-05 14:09:50.679095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838f47fa598e'
down_revision = '15cfedb47914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'is_draft')
    # ### end Alembic commands ###
