"""empty message

Revision ID: 8b0cb19f8e0d
Revises: 1516b659add3
Create Date: 2019-08-21 10:45:46.153823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0cb19f8e0d'
down_revision = '1516b659add3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('coordinator_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'coordinator_email')
    # ### end Alembic commands ###
