"""empty message

Revision ID: 8ce482222197
Revises: dae8f36249fb
Create Date: 2019-02-15 12:53:04.816503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce482222197'
down_revision = 'dae8f36249fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_participant', 'relationship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_participant', sa.Column('relationship', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
