"""empty message

Revision ID: 8e98024bd388
Revises: f7303aa04673
Create Date: 2019-01-30 16:59:32.046596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e98024bd388'
down_revision = 'f7303aa04673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_questionnaire', 'dependant_living_situation',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('home_questionnaire', 'self_living_situation',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_questionnaire', 'self_living_situation',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('home_questionnaire', 'dependant_living_situation',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
