"""empty message

Revision ID: 8f1f051dba65
Revises: 8ce482222197
Create Date: 2019-02-15 12:53:40.922564

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8f1f051dba65'
down_revision = '8ce482222197'
branch_labels = None
depends_on = None


def upgrade():
    relationship = postgresql.ENUM('self_participant', 'self_guardian', 'dependent', name='relationship')
    relationship.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_participant', sa.Column('relationship', sa.Enum('self_participant', 'self_guardian', 'dependent', name='relationship'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_participant', 'relationship')
    # ### end Alembic commands ###
    op.execute("DROP TYPE relationship;")
