"""empty message

Revision ID: 8f53dde47283
Revises: 17002734af75
Create Date: 2019-01-30 10:44:50.387995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f53dde47283'
down_revision = '17002734af75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardian_demographics_questionnaire', sa.Column('gender_identity', sa.String(), nullable=True))
    op.add_column('guardian_demographics_questionnaire', sa.Column('gender_identity_other', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guardian_demographics_questionnaire', 'gender_identity_other')
    op.drop_column('guardian_demographics_questionnaire', 'gender_identity')
    # ### end Alembic commands ###
