"""empty message

Revision ID: 90da62bcfacd
Revises: c895d9c662e9
Create Date: 2020-03-30 13:49:18.566060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90da62bcfacd'
down_revision = 'c895d9c662e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('covid19_categories', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'covid19_categories')
    # ### end Alembic commands ###
