"""empty message

Revision ID: 974db61e6508
Revises: e6defbf26a32
Create Date: 2019-09-12 21:34:08.445756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974db61e6508'
down_revision = 'e6defbf26a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zip_code', 'zip_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zip_code', sa.Column('zip_code', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
