"""empty message

Revision ID: 98c7920d1570
Revises: 5cdc5e06da9c
Create Date: 2019-01-25 13:48:55.909331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98c7920d1570'
down_revision = '5cdc5e06da9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stardrive_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guardian_demographics_questionnaire')
    op.drop_table('demographics_questionnaire')
    op.drop_table('contact_questionnaire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_questionnaire',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('can_leave_voicemail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('contact_times', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('street_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marketing_channel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_first_name_preferred', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('marketing_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_user.id'], name='contact_questionnaire_participant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contact_questionnaire_pkey')
    )
    op.create_table('demographics_questionnaire',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guardian_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_first_name_preferred', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('birth_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birth_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birth_sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('race_ethnicity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_english_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gender_identity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender_identity_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('race_ethnicity_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['stardrive_user.id'], name='demographics_questionnaire_guardian_id_fkey'),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_user.id'], name='demographics_questionnaire_participant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='demographics_questionnaire_pkey')
    )
    op.create_table('guardian_demographics_questionnaire',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('guardian_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('race_ethnicity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_english_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('relationship_to_child', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('race_ethnicity_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relationship_to_child_other', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['stardrive_user.id'], name='guardian_demographics_questionnaire_guardian_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='guardian_demographics_questionnaire_pkey')
    )
    op.drop_table('user_participant')
    op.drop_table('stardrive_participant')
    # ### end Alembic commands ###
