"""empty message

Revision ID: 9b14a3e90c8e
Revises: 7fbbdbbf8ead
Create Date: 2020-11-11 16:26:44.616121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b14a3e90c8e'
down_revision = '7fbbdbbf8ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('post_event_description', sa.String(), nullable=True))
    op.alter_column('study_user', 'status',
               existing_type=postgresql.ENUM('inquiry_sent', 'enrolled', name='study_user_status'),
               type_=sa.Enum('inquiry_sent', 'enrolled', name='study_user_status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_user', 'status',
               existing_type=sa.Enum('inquiry_sent', 'enrolled', name='study_user_status'),
               type_=postgresql.ENUM('inquiry_sent', 'enrolled', name='study_user_status'),
               existing_nullable=True)
    op.drop_column('event', 'post_event_description')
    # ### end Alembic commands ###
