"""empty message

Revision ID: 9b391c53128c
Revises: 725179176fb7
Create Date: 2019-01-16 10:24:39.687660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b391c53128c'
down_revision = '725179176fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_questionnaire', sa.Column('is_first_name_preferred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_questionnaire', 'is_first_name_preferred')
    # ### end Alembic commands ###
