"""empty message

Revision ID: a16b676fae54
Revises: 782d6f74af9f
Create Date: 2019-01-24 10:08:07.779273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16b676fae54'
down_revision = '782d6f74af9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_questionnaire', sa.Column('marketing_other', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_questionnaire', 'marketing_other')
    # ### end Alembic commands ###
