"""empty message

Revision ID: ae566f24d973
Revises: 838f47fa598e
Create Date: 2020-02-18 17:02:08.574872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae566f24d973'
down_revision = '838f47fa598e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stardrive_user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stardrive_user', 'last_login')
    # ### end Alembic commands ###
