"""empty message

Revision ID: bc81c8285922
Revises: e6defbf26a32
Create Date: 2019-09-12 09:50:34.414216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc81c8285922'
down_revision = 'e6defbf26a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('ages', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('study', sa.Column('ages', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'ages')
    op.drop_column('resource', 'ages')
    # ### end Alembic commands ###
