"""empty message

Revision ID: c0826f058bbf
Revises: 221895fbe0af
Create Date: 2020-02-27 10:05:48.151827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0826f058bbf'
down_revision = '221895fbe0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('languages', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'languages')
    # ### end Alembic commands ###
