"""empty message

Revision ID: c1a41dfb42c8
Revises: 398615e6b6d8
Create Date: 2019-05-09 10:45:37.816113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1a41dfb42c8'
down_revision = '398615e6b6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_organization_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key('event_location_id_fkey', 'event', 'location', ['id'], ['id'])
    op.drop_column('event', 'title')
    op.drop_column('event', 'zip')
    op.drop_column('event', 'phone')
    op.drop_column('event', 'last_updated')
    op.drop_column('event', 'website')
    op.drop_column('event', 'organization_id')
    op.drop_column('event', 'street_address1')
    op.drop_column('event', 'primary_contact')
    op.drop_column('event', 'description')
    op.drop_column('event', 'street_address2')
    op.drop_column('event', 'city')
    op.drop_column('event', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('street_address2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('primary_contact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('street_address1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('event_location_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key('event_organization_id_fkey', 'event', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###
