"""empty message

Revision ID: c3dd61fa0826
Revises: 126f90fe8789
Create Date: 2019-02-01 16:40:58.013200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dd61fa0826'
down_revision = '126f90fe8789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developmental_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('had_birth_complications', sa.Boolean(), nullable=True),
    sa.Column('when_motor_milestones', sa.String(), nullable=True),
    sa.Column('when_language_milestones', sa.String(), nullable=True),
    sa.Column('when_toileting_milestones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developmental_questionnaire')
    # ### end Alembic commands ###
