"""empty message

Revision ID: c8b3f9777c44
Revises: ddbcff08df14
Create Date: 2020-01-03 11:35:29.012125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b3f9777c44'
down_revision = 'ddbcff08df14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('num_visits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'num_visits')
    # ### end Alembic commands ###
