"""empty message

Revision ID: cb7a8db2c57f
Revises: 715890d8a5b4
Create Date: 2020-06-04 15:48:22.231916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb7a8db2c57f'
down_revision = '715890d8a5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webinar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webinar_link', sa.String(), nullable=True),
    sa.Column('survey_link', sa.String(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webinar_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webinar_user')
    op.drop_table('webinar')
    # ### end Alembic commands ###
