"""empty message

Revision ID: cf9f2ed356ab
Revises: 62150b1fb708
Create Date: 2020-04-20 15:05:12.110591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf9f2ed356ab'
down_revision = '62150b1fb708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identification_questionnaire', sa.Column('no_middle_name', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identification_questionnaire', 'no_middle_name')
    # ### end Alembic commands ###
