"""empty message

Revision ID: d9a7f4d4318e
Revises: 619598a63223
Create Date: 2019-02-04 14:45:06.020536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a7f4d4318e'
down_revision = '619598a63223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_diagnoses_questionnaire', sa.Column('developmental_other', sa.String(), nullable=True))
    op.add_column('clinical_diagnoses_questionnaire', sa.Column('genetic', sa.String(), nullable=True))
    op.add_column('clinical_diagnoses_questionnaire', sa.Column('genetic_other', sa.String(), nullable=True))
    op.add_column('clinical_diagnoses_questionnaire', sa.Column('medical_other', sa.String(), nullable=True))
    op.add_column('clinical_diagnoses_questionnaire', sa.Column('mental_health_other', sa.String(), nullable=True))
    op.drop_column('clinical_diagnoses_questionnaire', 'genetic_conditions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_diagnoses_questionnaire', sa.Column('genetic_conditions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clinical_diagnoses_questionnaire', 'mental_health_other')
    op.drop_column('clinical_diagnoses_questionnaire', 'medical_other')
    op.drop_column('clinical_diagnoses_questionnaire', 'genetic_other')
    op.drop_column('clinical_diagnoses_questionnaire', 'genetic')
    op.drop_column('clinical_diagnoses_questionnaire', 'developmental_other')
    # ### end Alembic commands ###
