"""empty message

Revision ID: da1abfa9434c
Revises: 3f38dd4854a8
Create Date: 2021-01-20 10:08:55.317124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da1abfa9434c'
down_revision = '3f38dd4854a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_session_step', sa.Column('target_prompt_level', sa.String(), nullable=True))
    op.add_column('chain_session_step', sa.Column('was_focus_step', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chain_session_step', 'was_focus_step')
    op.drop_column('chain_session_step', 'target_prompt_level')
    # ### end Alembic commands ###
