"""empty message

Revision ID: da4c50ed75ff
Revises: c39eabf2b27e
Create Date: 2019-05-02 12:58:04.051096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4c50ed75ff'
down_revision = 'c39eabf2b27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'city')
    op.drop_column('resource', 'county')
    op.drop_column('resource', 'image_caption')
    op.drop_column('resource', 'street_address1')
    op.drop_column('resource', 'zip')
    op.drop_column('resource', 'street_address2')
    op.drop_column('resource', 'state')
    op.drop_column('resource', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('street_address2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('street_address1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('image_caption', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
