"""empty message

Revision ID: dae8f36249fb
Revises: 632e0d0b5b5a
Create Date: 2019-02-06 11:01:30.437069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae8f36249fb'
down_revision = '632e0d0b5b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_currently_employed', sa.Boolean(), nullable=True),
    sa.Column('employment_capacity', sa.String(), nullable=True),
    sa.Column('has_employment_support', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['stardrive_participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['stardrive_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employment_questionnaire')
    # ### end Alembic commands ###
