"""empty message

Revision ID: dd72f4edfb71
Revises: 2960131e441a
Create Date: 2021-02-18 15:25:07.218891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd72f4edfb71'
down_revision = '2960131e441a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chain_session_step_participant_id_fkey', 'chain_session_step', type_='foreignkey')
    op.drop_constraint('chain_session_step_user_id_fkey', 'chain_session_step', type_='foreignkey')
    op.drop_column('chain_session_step', 'user_id')
    op.drop_column('chain_session_step', 'participant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_session_step', sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chain_session_step', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chain_session_step_user_id_fkey', 'chain_session_step', 'stardrive_user', ['user_id'], ['id'])
    op.create_foreign_key('chain_session_step_participant_id_fkey', 'chain_session_step', 'stardrive_participant', ['participant_id'], ['id'])
    # ### end Alembic commands ###
