"""empty message

Revision ID: ddbcff08df14
Revises: f955ff4cec32
Create Date: 2019-12-16 14:08:00.988184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbcff08df14'
down_revision = 'f955ff4cec32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_uva_education_content', sa.Boolean(), nullable=True))
    op.add_column('resource', sa.Column('video_code', sa.String(), nullable=True))
    op.drop_column('resource', 'video_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('video_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('resource', 'video_code')
    op.drop_column('resource', 'is_uva_education_content')
    # ### end Alembic commands ###
