"""empty message

Revision ID: deff06cbbec5
Revises: 5a928cbc36f0
Create Date: 2019-05-09 12:00:47.885033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deff06cbbec5'
down_revision = '5a928cbc36f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_category', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_category', 'type')
    # ### end Alembic commands ###
