"""empty message

Revision ID: ed30d9477d9f
Revises: 24c1b855eeeb
Create Date: 2020-10-02 22:14:47.572261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed30d9477d9f'
down_revision = '24c1b855eeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('should_hide_related_resources', sa.Boolean(), nullable=True))
    op.alter_column('study_user', 'status',
               existing_type=postgresql.ENUM('inquiry_sent', 'enrolled', name='study_user_status'),
               type_=sa.Enum('inquiry_sent', 'enrolled', name='study_user_status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_user', 'status',
               existing_type=sa.Enum('inquiry_sent', 'enrolled', name='study_user_status'),
               type_=postgresql.ENUM('inquiry_sent', 'enrolled', name='study_user_status'),
               existing_nullable=True)
    op.drop_column('resource', 'should_hide_related_resources')
    # ### end Alembic commands ###
