"""empty message

Revision ID: ef0dc145fcf9
Revises: 1a6ea20ed002
Create Date: 2020-12-04 16:09:41.046563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef0dc145fcf9'
down_revision = '1a6ea20ed002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chain_session_assessment_questionnaire', 'prompt_level',
               existing_type=postgresql.ENUM('none', 'shadow', 'partial_physical', 'full_physical', name='chainpromptlevel'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('study_user', 'status',
               existing_type=postgresql.ENUM('inquiry_sent', 'enrolled', name='study_user_status'),
               type_=sa.Enum('inquiry_sent', 'enrolled', name='study_user_status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_user', 'status',
               existing_type=sa.Enum('inquiry_sent', 'enrolled', name='study_user_status'),
               type_=postgresql.ENUM('inquiry_sent', 'enrolled', name='study_user_status'),
               existing_nullable=True)
    op.alter_column('chain_session_assessment_questionnaire', 'prompt_level',
               existing_type=sa.String(),
               type_=postgresql.ENUM('none', 'shadow', 'partial_physical', 'full_physical', name='chainpromptlevel'),
               existing_nullable=True)
    # ### end Alembic commands ###
