"""empty message

Revision ID: f543f7586a61
Revises: 57bbd20fabbc
Create Date: 2019-06-14 11:31:43.470532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f543f7586a61'
down_revision = '57bbd20fabbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stardrive_participant', sa.Column('has_consented', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stardrive_participant', 'has_consented')
    # ### end Alembic commands ###
