"""empty message

Revision ID: f602215ba612
Revises: 79c463336307
Create Date: 2018-12-20 13:11:07.369682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f602215ba612'
down_revision = '79c463336307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'last_updated')
    # ### end Alembic commands ###
