"""empty message

Revision ID: f7303aa04673
Revises: 037429037ea4
Create Date: 2019-01-30 14:42:35.719716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7303aa04673'
down_revision = '037429037ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_questionnaire', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.add_column('contact_questionnaire', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact_questionnaire', 'stardrive_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'contact_questionnaire', 'stardrive_participant', ['participant_id'], ['id'])
    op.add_column('demographics_questionnaire', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.add_column('demographics_questionnaire', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'demographics_questionnaire', 'stardrive_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'demographics_questionnaire', 'stardrive_participant', ['participant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demographics_questionnaire', type_='foreignkey')
    op.drop_constraint(None, 'demographics_questionnaire', type_='foreignkey')
    op.drop_column('demographics_questionnaire', 'user_id')
    op.drop_column('demographics_questionnaire', 'participant_id')
    op.drop_constraint(None, 'contact_questionnaire', type_='foreignkey')
    op.drop_constraint(None, 'contact_questionnaire', type_='foreignkey')
    op.drop_column('contact_questionnaire', 'user_id')
    op.drop_column('contact_questionnaire', 'participant_id')
    # ### end Alembic commands ###
