"""empty message

Revision ID: fd907adff7c3
Revises: c8b3f9777c44
Create Date: 2020-01-03 12:34:45.555245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd907adff7c3'
down_revision = 'c8b3f9777c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('contact_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'contact_email')
    # ### end Alembic commands ###
