"""empty message

Revision ID: fe36baca652f
Revises: 0a96d64ea510
Create Date: 2020-01-28 11:53:14.838401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe36baca652f'
down_revision = '0a96d64ea510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stardrive_user', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='role'),
               type_=sa.Enum('admin', 'researcher', 'editor', 'user', name='role'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stardrive_user', 'role',
               existing_type=sa.Enum('admin', 'researcher', 'editor', 'user', name='role'),
               type_=postgresql.ENUM('admin', 'user', name='role'),
               existing_nullable=True)
    # ### end Alembic commands ###
