name: CI
on: [push, pull_request, workflow_dispatch]
env:
  FLASK_APP: ${{ github.workspace }}/backend/app/__init__.py
  FLASK_ENV: test
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Configure VM for Elasticsearch
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get -y install apache2 apache2-utils apache2-dev
          cd backend
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
          cd ..
      - name: Run tests
        run: |
          # Set the home directory
          export HOME_DIR=`pwd`
          BACKEND_PATH="${HOME_DIR}/backend"
  
          echo -e '\n\n*** Starting tests in backend ***\n\n'
          cd $BACKEND_PATH
          export FLASK_APP="${BACKEND_PATH}/app/__init__.py"
          python -m unittest discover -s tests -t tests
