name: CI
on: [push, pull_request, workflow_dispatch]
env:
  FRONTEND_PATH: ${{ github.workspace }}/frontend
  BACKEND_PATH: ${{ github.workspace }}/backend
  FLASK_APP: ${{ github.workspace }}/backend/app/main.py
  FLASK_ENV: local
  PYTHONPATH: ${{ github.workspace }}/backend
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.1]
        node-version: [22.3.0]
        poetry-version: [1.8.4]
    steps:
      - uses: actions/checkout@v3
      - name: Configure VM for Elasticsearch
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Start Elasticsearch and PostgreSQL
        run: docker compose up -d db es
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Apache
        run: |
          sudo apt update
          sudo apt-get -y install apache2 apache2-utils apache2-dev
      - name: Install Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Setup virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        id: cache-deps
        with:
          path: .venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install and cache dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Install the project
        run: poetry install

      - name: Create config files
        run: |
          cd $BACKEND_PATH
          cp config/template.env .env
          echo "GOOGLE_MAPS_API_KEY = ${{secrets.GOOGLE_MAPS_API_KEY}}" >> .env
          echo "GOOGLE_ANALYTICS_API_KEY = ${{secrets.GOOGLE_ANALYTICS_API_KEY}}" >> .env
          echo "GOOGLE_TAG_MANAGER_ID = ${{secrets.GOOGLE_TAG_MANAGER_ID}}" >> .env
          echo "MASTER_EMAIL = ${{secrets.MASTER_EMAIL}}" >> .env
          echo "MASTER_PASS = ${{secrets.MASTER_PASS}}" >> .env
          
          mkdir -p instance
          cp config/ci.py instance/config.py
          cp config/testing.py instance/testing.py

      - name: Initialize database and search index
        run: |
          cd $BACKEND_PATH
          poetry 
          echo "FLASK_APP = $FLASK_APP"
          pwd
          ls -al .

          echo -e '\n\n*** Running Alembic database migrations... ***\n\n'
          
          poetry run flask clear-db
          poetry run flask upgrade-db
          poetry run flask init-db

          echo -e '\n\n*** Updating Elasticsearch index... ***\n\n'
          poetry run flask init-index
      - name: Run backend unit tests
        run: |
          cd $BACKEND_PATH
          pwd
          ls -al .
          
          echo -e '\n\n*** Running backend unit tests... ***\n\n'
          poetry run coverage run -m unittest discover -s tests -t tests
      - name: Install frontend dependencies
        run: |
          cd $FRONTEND_PATH
          npm install
      - name: Run frontend unit tests
        run: |
          cd $FRONTEND_PATH
          ng test frontend
      - name: Export coverage report to XML
        shell: bash
        run: |
          cd $BACKEND_PATH
          pwd
          ls -al .
          coverage xml
          ls -al .
      # Hack to rewrite paths in coverage support so SonarCloud can parse them properly.
      - name: Rewrite coverage source path for SonarCloud
        shell: bash
        run: |
          sed -i \
          's/<source>\/home\/runner\/work\/autismdrive\/autismdrive/<source>\/github\/workspace/g' \
          /home/runner/work/autismdrive/autismdrive/backend/coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.SONARCLOUD_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
